version: 0.0
os: linux
files:
  - source: /vendor/
    destination: /home/ec2-user/serverpod/upload/vendor/
  - source: /yahu1031/
    destination: /home/ec2-user/serverpod/upload/yahu1031/
hooks:
  BeforeInstall:
    - location: yahu1031/aws/scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: yahu1031/aws/scripts/start_server
      timeout: 300
      runas: root
